---
name: Packer
on:
  push:
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install qemu-kvm
        run: sudo apt-get update && sudo apt-get install qemu-kvm -y
      - name: Validate
        run: packer validate packer.json 
      - name: Build
        run: packer build -color=false -on-error=abort -var=accelerator=tcg packer.json
      - name: Upload image to s3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.S3_AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.S3_AWS_BUCKET }}
          source_dir: 'builds/'