---
name: Packer
on:
  push:
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install xmllint
        run: sudo apt-get qemu-kvm -y

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer.json

      # build artifact
      - name: Build Artifact
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: packer.json

      # additional steps to process artifacts