---
name: Packer
on:
  push:
  schedule:
    # Run it daily
    - cron: '0 0 * * *'
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Validate
        run: packer validate packer.json 
      - name: Check hash
        run: ./check.sh
      - name: Commit change
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Github Actions CI
          author_email: pentesterwtf-ci@c0refailure.com
          message: 'update hash'
          add: 'packer.json'
