---
name: Packer
on:
  push:
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer.json

      # build artifact
      - name: Packer build
        uses: enr0s/packer-qemu-action@v1.0
        with:
          templateFile: 'packer.json'
          workingDir: '.'

      # additional steps to process artifacts