---
name: Packer
on:
  push:
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install qemu-kvm
        run: sudo apt-get update && sudo apt-get install qemu-kvm -y
      - name: Validate
        run: packer validate packer.json 
      - name: Build
        run: PACKER_LOG=1 packer build -color=false -on-error=abort -var=accelerator=tcg packer.json